#!/usr/bin/env python3
"""Pack the inventoried Lima/UTM x86 firmware; no runtime extraction.

SPDX-License-Identifier: GPL-2.0-or-later
"""
import argparse
import hashlib
import json
from pathlib import Path

# Explicit inventory, not a glob: never accidentally embed ARM/RISC-V blobs.
ASSETS = """
bios.bin bios-256k.bin bios-microvm.bin
edk2-x86_64-code.fd edk2-x86_64-secure-code.fd
edk2-i386-code.fd edk2-i386-secure-code.fd
edk2-i386-vars.fd edk2-i386-secure-vars.fd edk2-licenses.txt
kvmvapic.bin linuxboot.bin linuxboot_dma.bin multiboot.bin multiboot_dma.bin pvh.bin
qboot.rom
pxe-e1000.rom pxe-eepro100.rom pxe-ne2k_pci.rom pxe-pcnet.rom
pxe-rtl8139.rom pxe-virtio.rom
efi-e1000.rom efi-e1000e.rom efi-eepro100.rom efi-ne2k_pci.rom efi-pcnet.rom
efi-rtl8139.rom efi-virtio.rom efi-vmxnet3.rom
vgabios.bin vgabios-ati.bin vgabios-bochs-display.bin vgabios-cirrus.bin
vgabios-qxl.bin vgabios-ramfb.bin vgabios-stdvga.bin vgabios-virtio.bin
vgabios-vmware.bin
""".split()


# Keep the complete bundled keyboard-layout set, including non-Latin layouts.
# These are architecture-independent text, not non-x86 firmware.
KEYMAPS = """
ar bepo cz da de de-ch en-gb en-us es et fi fo fr fr-be fr-ca fr-ch
hr hu is it ja lt lv mk nl no pl pt pt-br ru sl sv th tr
""".split()
ASSETS += ["keymaps/" + name for name in KEYMAPS]


def generate(asset_dir, output_dir):
    root = Path(__file__).resolve().parents[1]
    inputs = {name: asset_dir / name for name in ASSETS}
    inputs.update({
        "firmware-notices.txt": root / "pc-bios/README",
        "firmware-COPYING": root / "COPYING",
        "firmware-COPYING.LIB": root / "COPYING.LIB",
    })
    # Validate everything before replacing any generated output.
    contents = {name: path.read_bytes() for name, path in inputs.items()}
    blob = bytearray()
    entries = []
    table = ["/* Generated by scripts/gen-builtin-resources.py; do not edit. */",
             "static const QemuBuiltinResource builtin_resources[] = {"]
    for name, data in sorted(contents.items()):
        if not data:
            raise ValueError(f"Empty resource: {name}")
        blob.extend(b"\0" * (-len(blob) % 16))
        offset = len(blob)
        table.append(f'    {{ "{name}", qemu_builtin_blob + {offset}, {len(data)} }},')
        entries.append({"name": name, "offset": offset, "size": len(data),
                        "sha256": hashlib.sha256(data).hexdigest()})
        blob.extend(data)
    table.append("};")
    manifest = {"format": 1, "resources": entries,
                "resource_bytes": sum(e["size"] for e in entries),
                "blob_bytes": len(blob),
                "blob_sha256": hashlib.sha256(blob).hexdigest()}
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "builtin-data.bin").write_bytes(blob)
    (output_dir / "builtin-table.inc").write_text("\n".join(table) + "\n")
    (output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"Embedded {len(entries)} resources: {manifest['resource_bytes']} bytes "
          f"({len(blob)} bytes with alignment)")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--asset-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path,
                        default=Path(__file__).resolve().parents[1] /
                        "util/builtin-resources")
    args = parser.parse_args()
    generate(args.asset_dir, args.output_dir)


if __name__ == "__main__":
    main()
